controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  wheeled_bipedal_rl_controller:
    type: rl_controller/WheeledBipedalRLController



